spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ap_db_youtube
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    hibernate:
      ddl-auto: none